### ISSUE TITLE
Základní funkce

### ISSUE THREAD

**Issue by Lukadoss** [Lukadoss/slovnik#1]
admin/všichni? - správa obcí - seznam
admin - správa mluvčích

**Comment by honzaseda** [comment]
nevidim žádnej progress, velký špatný

**Comment by Lukadoss** [comment]
? stipendium za den otevřených dveří ?
admin - správa mluvčích -> pouze editace/smazání
admin (pouze) - správa obcí -> registrovaní uživatelé by měli možnost pouze navrhnout neznámou obec - vytvořit ji však musí admin/správce
