### ISSUE TITLE
Bugy v diakritice z DB.. zase

### ISSUE THREAD

**Issue by Lukadoss** [Lukadoss/slovnik#14]
abeceda - Ĺ, Ź, Ć
stejně se to bere na znaky bez čárky, tak bych je prostě manuálně odebral

**Comment by Vrbikk** [comment]
potvrzuji výskyt těchto chyb i na mojem webu, pls oprav to dik

**Comment by fifal** [comment]
dneska se mi stalo to samé. kde může být chyba????????
